name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - name: Publish
        run: cargo doc --no-deps && cargo publish --token ${{secrets.CARGO_TOKEN}}